### ISSUE TITLE
Post detail return "404 page not found"

### ISSUE THREAD

**Issue by kubido** [joway/hugo-theme-yinyang#1]
When accessing post detail from homepage returning "404 page not found"

**Comment by nickolay-github** [comment]
yes, same problem

**Comment by kubido** [comment]
I'm new with hugo. the solution is to rename the `post` directory to `_default'

**Comment by joway** [comment]
Hi, @kubido 

what's your hugo version? I write the theme follow the docs: https://gohugo.io/templates/single-page-templates/

**Comment by joway** [comment]
@nickolay-github can you use hugo v0.50 and have a retry?

**Comment by dayuoba** [comment]
i have the same problem with yinyang theme, my hugo version 0.54 and i use `hugo new en/mypost.md` to create my page.

**Comment by joway** [comment]
@dayuoba  Can you using `tree ./content` let me know your project structure?

**Comment by joway** [comment]
Hi, @dayuoba @kubido  I have reproduce your problem. It has been fixed in latest master branch, thanks very much!

**Comment by joway** [comment]
#2
