### ISSUE TITLE
disqus section not show

### ISSUE THREAD

**Issue by XiaochenCui** [joway/hugo-theme-yinyang#17]
I have set 
```
[params]
disqus = "xxx"
```

But there is no disqus section, where xxx is my disqus account

**Comment by XiaochenCui** [comment]
Here comes the blog address: https://cuixiaochen.com/

**Comment by joway** [comment]
@XiaochenCui  Could you post your full `config.yml`? I cannot reproduce your case.

Here is some related codes: https://github.com/joway/hugo-theme-yinyang/blob/74e4139bf0ca6102e2fe6cfa4b633ee2180d1ffd/layouts/_default/single.html#L47

https://github.com/joway/hugo-theme-yinyang/blob/968ccd79a8e45ec5f5fe8b5d3d91b370edb874c0/layouts/partials/disqus.html

**Comment by XiaochenCui** [comment]
config.yaml:

https://github.com/XiaochenCui/XiaochenCui.github.io/blob/hugo/config.toml

**Comment by joway** [comment]
@XiaochenCui  It's bug, thanks!
