### ISSUE TITLE
Remove exampleSite to use the theme mnimal & clean as git submodule

### ISSUE THREAD

**Issue by LeoWinterDE** [joway/hugo-theme-yinyang#18]
The folder 'exampleSite' inside the master branch is somewhat unpractical if you use the theme as a git submodule for any Hugo page.

`cd themes && git submodule add https://github.com/joway/hugo-theme-yinyang yinyang`

https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#use-hugo-themes-with-netlify

**Comment by joway** [comment]
@LeoWinterDE Hi, there are lots of Hugo themes includes exampleSite. And I don't know what error happened on your side when `exampleSite` included? What's `somewhat unpractical if you use the theme as a git submodule for any Hugo page`?
