### ISSUE TITLE
How can I enable word wrap?

### ISSUE THREAD

**Issue by jakeoung** [joway/hugo-theme-yinyang#21]
Thanks for the wonderful theme. I have only one issue that English words are not wrapped. Could you check it?

**Comment by joway** [comment]
@jakeoung Hi, which part English words not wrapped?

**Comment by jakeoung** [comment]
For example, in https://themes.gohugo.io//theme/hugo-theme-yinyang/posts/hugoisforlovers/ the following sentence is not word-wrapped.

Hugo has its own example site which happens to also be the documentation site you are readi
ng right now.

(But I expect:)
Hugo has its own example site which happens to also be the documentation site you are readi
ng right now.

**Comment by joway** [comment]
@jakeoung Thanks for your issue, I had fixed it https://github.com/joway/hugo-theme-yinyang/commit/e78d1ebf7f06d58a4717b6dcc46558cb4c0d5d8c

**Comment by oneway101** [comment]
Hi! I wanted to let you know that the word-wrap issue is still present in the new versions if your blog is written in English.

**Comment by joway** [comment]
@oneway101  did you use the latest version? it looks well on https://themes.gohugo.io//theme/hugo-theme-yinyang/posts/hugoisforlovers/
