### ISSUE TITLE
Customization Help

### ISSUE THREAD

**Issue by koraylinux** [joway/hugo-theme-yinyang#24]
Hello! I know it's not your problem and theme works great but i have 2 issues that i could not handle myself. My blog address is koraybicer.com.tr

I want to remove 2 things.

1. The date. That 2020 i am trying to erase.
2. Black lines on up and down.

I will gladly appreciated if you can help me.

**Comment by joway** [comment]
Hi @koraylinux , thanks for using yinyang.

I add a new params `extraCSSFiles` to make you can add your own CSS files, you can follow the [README](https://github.com/joway/hugo-theme-yinyang#extra-css-files).
