### ISSUE TITLE
Tags support

### ISSUE THREAD

**Issue by timothy-makobu** [joway/hugo-theme-yinyang#25]
The theme is great, thanks for making it.

Would it be possible to add a way to have:
- A list of tags on the home page (like on the right side), and below each post on the front page listing and below the post when it's opened

**Comment by joway** [comment]
@timothy-makobu  Hi，thanks for using yinyang!

I think what you need is not a general feature. It should be better to fork the theme and custom the style you want.

**Comment by timothy-makobu** [comment]
Alright, thanks.
