### ISSUE TITLE
extraCSSFiles param breaks the theme

### ISSUE THREAD

**Issue by wipash** [joway/hugo-theme-yinyang#27]
When defining extraCSSFiles like this:

```toml
[params]
  extraCSSFiles = ["css/site.css"]
```

Hugo fails to render the page, errors out with:
```
ERROR 2020/07/28 11:47:08 render of "page" failed: execute of template failed: template: _default/single.html:3:3: executing "_default/single.html" at <partial "head.html" .>: error calling partial: "/home/sean/sean.mcgrath.nz/themes/yinyang/layouts/partials/head.html:45:39": execute of template failed: template: partials/head.html:45:39: executing "partials/head.html" at <.Site.Params.staticPrefix>: can't evaluate field Site in type interface {}
```

I have found the fix is to add a `$` to `.Site.Params.staticPrefix` in the `head.html` partial on line 45:
```html
  {{ range .Site.Params.extraCSSFiles -}}
  <link rel="stylesheet" href="{{ $.Site.Params.staticPrefix }}{{ . | relURL }}">
  {{- end }}
```

I believe this is because inside a `range` the template engine binds `.` to the value in the range. `$.` references the global values, which fixes the problem.

**Comment by joway** [comment]
@wipash  Thanks for your issue! I fixed it in https://github.com/joway/hugo-theme-yinyang/commit/2da0a694c4db598a8240e76be541d0c39aef571b

**Comment by tami5** [comment]
Thankkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkksssssssssss I was struggling with changing the theme I had to go into hugo docs/. Great theme
