### ISSUE TITLE
Page build failure

### ISSUE THREAD

**Issue by yagudin** [joway/hugo-theme-yinyang#3]
Trying to update my personal blog, I got the following email from GitHub:

> The page build failed for the `master` branch with the following error:

> The tag `image` on line 129 in `themes/yinyang/exampleSite/content/en/post/migrate-from-jekyll.md` is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/.

I tried to exclude the file by adding `exclude: ['themes/yinyang/exampleSite/content/en/post/migrate-from-jekyll.md']` to my `config.toml`, but it didn't help.

**Comment by joway** [comment]
Hi @yagudin, thanks for your report!

hugo is not jekyll, github cannot build your hugo blog.
