### ISSUE TITLE
请问我安装后,代码高亮是白色背景,不是黑色的,请问怎么设置主题

### ISSUE THREAD

**Issue by nandisec** [joway/hugo-theme-yinyang#34]
[![yzDkv9.png](https://s3.ax1x.com/2021/02/26/yzDkv9.png)](https://imgtu.com/i/yzDkv9)

如图,代码块加载,背景色始终是 #fff ,修改了index.css 也没有效果,是不是bug

**Comment by joway** [comment]
@nandisec 你需要 debug 下你的 css ，主题本身不支持大幅度修改背景色，很多别的配套设计可能会有问题
