### ISSUE TITLE
需要凸显引用

### ISSUE THREAD

**Issue by ChungZH** [joway/hugo-theme-yinyang#37]
![image](https://user-images.githubusercontent.com/42088872/135597215-3d2401e2-d9a9-4795-a62f-2073889d6e07.png)

如图，难以区分正文与引用（`>` 语法）。希望能在引用左边加一条竖线之类的

**Comment by joway** [comment]
@ChungZH Thanks. Will be fixed later.

**Comment by joway** [comment]
@ChungZH fixed https://github.com/joway/hugo-theme-yinyang/commit/fe15a5323e28444547c4ab216e366494c1621ebc
