### ISSUE TITLE
手机端无法显示文章标签

### ISSUE THREAD

**Issue by Garhve** [joway/hugo-theme-yinyang#41]
如图，电脑端可以显示但手机端不行
![手机端](https://sm.ms/image/EyY9gaRxKHeBzTO)
![电脑端](https://sm.ms/image/RaKsA2duj3NZ4ey)
另外，想请问下你个人主页是和博客同一个Hugo项目吗？如果是，请问是怎么实现的？谢谢

**Comment by joway** [comment]
@Garhve 图片显示不出来

**Comment by Garhve** [comment]
![电脑端](https://s2.loli.net/2022/05/23/RaKsA2duj3NZ4ey.png)


![手机端](https://s2.loli.net/2022/05/23/EyY9gaRxKHeBzTO.jpg)

**Comment by Garhve** [comment]
> 

图片在上面

**Comment by joway** [comment]
这个是故意的，因为展示不好
