### ISSUE TITLE
exampleSite/content/en/post 拼写错误，当为 exampleSite/content/en/posts

### ISSUE THREAD

**Issue by Zhang-Siyang** [joway/hugo-theme-yinyang#7]
Hugo新手，顺便请教一下为什么`hugo new  cn/posts/Hello-Hugo.md`后仍然在content/en下新建了cn/posts，想要在content/cn新建文件

**Comment by joway** [comment]
fixed it. https://github.com/joway/hugo-theme-yinyang/commit/2b085f77fcc7483e9d8a992d48bf1f17715f4623

Yes, when you did `hugo new cn/posts/Hello-Hugo.md` , it seems will create post files in `content/en`. But I dont see any wrong in my theme, so I think it may be a bug of hugo itself.

**Comment by joway** [comment]
So... For me, I use `cp` as a solution

**Comment by Zhang-Siyang** [comment]
多谢多谢
