### ISSUE TITLE
Why the RSS link in footer is 'atom.xml' ? Hugo provide 'index.xml' for us 🤔

### ISSUE THREAD

**Issue by Zhang-Siyang** [joway/hugo-theme-yinyang#8]
The default path of RSS file is just in public/index.xml, can you explain why you chose the 'atom.xml' ?

I have to rename index.xml into atom.xml ...

Have a nice day😊.

英语很差，词汇量也低，若有用词不当和言语冒犯请斧正，谢谢您。您也可以看看Hugo默认生成的HTML，head有 `<link href="/index.xml" rel="alternate" type="application/rss+xml" title="Siyang&#39;s Blog">` 以供RSS嗅探器发现的

**Comment by joway** [comment]
Hi, Siyang,

The yinyang theme does not hard code the RSS link, so I don't know why you need to rename the `index.xml`.

My old blog system use `atom.xml`  as the RSS link, so I have to compatible with it ......

**Comment by Zhang-Siyang** [comment]
Got it, yesterday I check the `git log` of your work, i found 52fa41d75f15cf89fe456a8b7f5978412ed48149.

But I still have a question, if someone use the exampleSite to quick-look your theme, I think the `Subscribe` will not work. Because Hugo would not generate rss file in /atom.xml, actually, is /index.xml

It will seem that your theme have some problem. 

---

Chinese version:
为防俺英文没说清，用中文重述一遍：

我昨天心血来潮查看您是如何开发yinyang的，发现新近在页脚添加了RSS链接，应该是给那些不习惯从HTML源码寻找RSS地址的人用的吧。

Hugo默认生成的RSS文件存放在/index.xml，我猜测您的网站也是手动将index.xml重命名为atom.xml吧？新手未加注意就使用了您提供的exampleSite会发现，怎么访问不了atom.xml呢？他们可能不会察觉public目录下没有atom.xml。

所以我个人看来将Subscribe对应的链接设置为/index.xml比较好，嗯……怎么说才比较委婉呢，把工作和个人分开吧。

**Comment by joway** [comment]
oh, it should be a mistake, thanks! I have replace the rss link, https://github.com/joway/hugo-theme-yinyang/commit/3821c9a78d76e3fbeb9288779e90d1150135db19

**Comment by Zhang-Siyang** [comment]
How to say it? Pleasant cooperation?😘
